language: php
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install

script: vendor/bin/phpunit --configuration phpunit.xml

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly